### ISSUE TITLE
[WDS] Disconnected! Invalid Host/Origin header

### ISSUE THREAD

**Issue by iksent** [dgwyer/wp-react-plugin#8]
I am working on my localhost, and was getting these errors:

```
[WDS] Disconnected!
Invalid Host/Origin header
```

This issue helps me: https://github.com/webpack/webpack-dev-server/issues/1604

This is the solution:
```
module.exports = {
  // ...
  devServer: {
    disableHostCheck: true
  }
  // ...
};
```

UPD:

Okay, also it can be fixed by adding your real host in ```webpack.config.js```:
```
    devServer: {
      host: "wp-local.com", <---- here
      ...
    }
```

**Comment by dgwyer** [comment]
Thanks for reporting this. I've updated the Webpack config to include this.
