### ISSUE TITLE
Should add @babel/plugin-proposal-class-properties

### ISSUE THREAD

**Issue by iksent** [dgwyer/wp-react-plugin#9]
If you will use state like this:

```
export default class Example extends Component {
    state = {
        test: false
    };
    ...
```
You will get this error:
Support for the experimental syntax 'classProperties' isn't currently enabled

So you should add `@babel/plugin-proposal-class-properties` package.

**Comment by dgwyer** [comment]
Thanks for reporting this. It's now fixed.
